### ISSUE TITLE
Question: UPnP forward

### ISSUE THREAD

**Issue by hofq** [ich777/docker-openvpn-client#1]
Hey Christoph,

i have the OpenVPN Client in combination with an qbittorrent instance running. 

As i understand [that Article](https://surfshark.com/blog/vpn-port-forwarding) from my VPN Provider correctly, they support UPnP.

Is the Container forwarding the UPnP Traffic? Because i have some issues with that.

**Comment by ich777** [comment]
Hi!
Hmmmm, never used UPnP for a VPN and also wouldn't recommend that you do so...
But from my understanding this will only work if everything is on the same network but your router has then a different network or what is the exact issue?
TBH I've only forked the container and modernized the script a bit so that is in a working state again from @dperson but I don't see a reason why the container shouldn't forward UPnP requests.

**Comment by hofq** [comment]
okay, thanks
