### ISSUE TITLE
local net plus openvpn-client

### ISSUE THREAD

**Issue by davew723** [ich777/docker-openvpn-client#14]
I was wondering if you might have any guidance on this configuration.  I'm attempting to use this docker-openvpn-client project via the unraid openvpn-client app.  The issue I'm running into is I would like to serve immich thru the openvpn-client but it has a dependent service of postgres.  So my desired configuration is like the below.

<postgres docker> <- local net -> <immich docker> <- openvpn-client.container net -> openvpn-client <-> openvpn-server <- browser.

Docker run only allows one --net on startup.  I can connect a second network after startup.  I'm not sure if that is the best approach.  (I also don't think there is a way to automate that in unraid?  I realize this question is out of scope.)

Any recommendations how else to best deploy this configuration with this project?

**Comment by ich777** [comment]
@davew723 you could always allow the container to a subnet with `ROUTE` and the subnet, like described here in [this](https://github.com/ich777/docker-openvpn-client?tab=readme-ov-file#routing-for-local-access-to-non-http-proxy-able-ports) example.
So to speak create a new Variable in the Unraid template with the key: `ROUTE` and as the value the subnet that you want to give access to eg: `192.168.0.0/24`
However that defeats somehow the purpose of the OpenVPN container since it has then access to your subnet.

I would recommend that you put all containers into the network from OpenVPN for simplicity and that's how I would set it up.
If you are doing it that way don't forget you have to change the IPs to the containers in the config files or webui for Immich.

**Comment by ich777** [comment]
Can I close this issue or do you have any further questions?

**Comment by davew723** [comment]
Yes.  Thanks you I got things working!
