### ISSUE TITLE
Hard coding "eth0" causes an issue when using podman

### ISSUE THREAD

**Issue by pablos-here** [ich777/docker-openvpn-client#7]
Hi,
 
It seems `docker` uses `eth0` and `podman` uses `tap0`.  Currently, `start-server.sh` hard codes `eth0`.

To support both `docker` and `podman`, would it be possible to refactor `start-server.sh` to determine the tap at run time?

For example, the following code in `start.sh` will compute the tap device:

```shell
TAP=$(ip --brief a | grep -v '^lo' | awk '{ print $1}')
export TAP
```

`start-server.sh` would need to be modified to use `$TAP` instead of `eth0`

At the moment, I am not skilled at creating PRs.  :\

If there's interest in making the above change, I can make the change in my local copies and suss out any other issues.

Please let me know.

Thx a lot!

**Comment by ich777** [comment]
@pablos-here I have now modified the container so that you can create a environment variable called `INTERFACE` where you could put in your case `tap0`, by default it is of course `eth0`.

Hope that is also a suitable solution for you. I really don't want to make it auto detect since it can and most definitely will fail for some users.

**Comment by pablos-here** [comment]
Whoa, that's awesome!  Thank you so much!

I agree with you that auto-detect can be problematic.  In fact, while out, I was thinking of having an environment variable override to my proposal.  However, I like your idea better.  \o/
