### ISSUE TITLE
unable to connect to local network from Unraid via Bridge

### ISSUE THREAD

**Issue by Gurnox** [ich777/docker-openvpn-client#9]
Hello! 

Just updated to the latest version and can no longer connect from the container to/from my local network. I'm using the container as a VPN gateway for another application. 

So: 

curl localhost:[portno] from the container console and curl [container_ip]:[container_port] from the Unraid server work fine whereas: 

curl [unraid_server_ip]:[port] from a machine on my local network does not. 

Can't ping the local network from the container console either. Container and app using it are connecting to the Internet/VPN just fine. 

Extra parameters are default other than adding a local DNS server. 

This log entry doesn't seem familiar, but may be a red-herring or me mis-remembering: 

2023-06-13 09:41:15 WARNING: You have specified redirect-gateway and redirect-private at the same time (or the same option multiple times). This is not well supported and may lead to unexpected results

Thanks!

**Comment by ich777** [comment]
On what Unraid version are you?

Please post your `docker run` command.

**Comment by Gurnox** [comment]
Version 6.11.5

Docker run command is: 
```
docker run
  -d
  --name='OpenVPN-GB'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="[redacted]"
  -e HOST_CONTAINERNAME="OpenVPN-GB"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/openvpn-client.png'
  -p '6881:6881/tcp'
  -p '6881:6881/udp'
  -p '8080:8080/tcp'
  -v '/mnt/cache/appdata/openvpn-client':'/vpn':'rw'
  --device='/dev/net/tun'
  --cap-add=NET_ADMIN
  --dns=[redacted]
  --sysctl net.ipv6.conf.all.disable_ipv6=0 'ich777/openvpn-client'
```

**Comment by ich777** [comment]
I have a user with a similar issue, you can always revert back to the last version by changing the repository in the template to:
`ich777/openvpn-client:28`

My suspicion is that it has something to do with `6.11.5`, on `6.12.0-rc` series I have no issues running the container, I've now also tried pings from different containers/machines on my network and it is working just fine.

**Comment by Gurnox** [comment]
Back in business now. I'll stick at that version for now and upgrade again when there's a stable release of 6.12

Thanks for your help!

**Comment by ich777** [comment]
@Gurnox you can go back to: `ich777/openvpn-client` I have now tagged build `28` as latest again, sorry for the inconvenience.

**Comment by Gurnox** [comment]
Not a problem at all. Thanks again!

**Comment by rafaelbiriba** [comment]
I have a similar issue!
I am unable to access my container internal port that is proxied via the openvpn client.
I also have 

```
2025-01-11 01:48:01 WARNING: You have specified redirect-gateway and redirect-private at the same time (or the same option multiple times). This is not well supported and may lead to unexpected results
```
in my logs.

Unraid 6.12 here.

**Comment by ich777** [comment]
> I have a similar issue! I am unable to access my container internal port that is proxied via the openvpn client. I also have
> 
> ```
> 2025-01-11 01:48:01 WARNING: You have specified redirect-gateway and redirect-private at the same time (or the same option multiple times). This is not well supported and may lead to unexpected results
> ```
> 
> in my logs.
> 
> Unraid 6.12 here.

Please post your Diagnostics alongside with a screenshot from the Docker template that you are proxying and a screenshot from the OpenVPN-Client template.

**Comment by rafaelbiriba** [comment]
I tried everything i could think off!!

storagenode-rio exposes 14003 door.
acessing 192.168.27.11:14003 does not work.

In comparison, storagenode exposes 14002 (is the same container) i am running one more and i want to hide behind a vpn.

![Screenshot 2025-01-11 at 13 03 52](https://github.com/user-attachments/assets/b6badf11-38ee-475d-ae87-d55bc49d940d)

![Screenshot 2025-01-11 at 13 00 35](https://github.com/user-attachments/assets/61b48762-2da2-4a25-90bf-a06c5f3b95f3)
![Screenshot 2025-01-11 at 13 00 07](https://github.com/user-attachments/assets/acee990e-9256-4990-a394-aea6803cb053)

**Comment by ich777** [comment]
> storagenode-rio exposes 14003 door.
> acessing 192.168.27.11:14003 does not work.

Sorry but in the screenshot you provided storagenode-rio is not running.

I‘m not familiar with storagenode at all but what is the variabel VNCPORT;1
This does not belong in the OpenVPN Client template.
Is this how you configure storagenode?

It seems like, at least to me, this is a configuration issue.

**Comment by rafaelbiriba** [comment]
When is running is not working.
VPNPORT_1 is part of your redme file
This is not how you expose the port?

**Comment by ich777** [comment]
This is not how this works and what it's meant for.

Please read the description from the container again.
In the OpenVPN-Client container you just have to create a port mapping like in the storagenode-rio container with the container and host port set to 14003

Here is a screenshot:
![grafik](https://github.com/user-attachments/assets/394f4f3c-95cd-4e60-a28c-a1126bb8f4e9)
(I would also recommend that you specify a IP in the Ping IP variable since this is way safer if DNS for some reason is not working)

However I would also recommend that you upgrade to Unraid 7.0.0 stable since it is now possible to specify a container network like this:
![grafik](https://github.com/user-attachments/assets/0ed85f60-4a97-42ca-9977-320ad1c47027)

**Comment by rafaelbiriba** [comment]
Thanks for the reply.
Sadly it is still not working for me.

As you can see, the container is up but the 14003 door is not working.
The same container below, binding on 14002 without the vpn works normally.

Any idea what else i can try?

![Screenshot 2025-01-11 at 15 50 06](https://github.com/user-attachments/assets/a43c5bdf-adc9-484b-b742-406509f25616)
![Uploading Scree
![Screenshot 2025-01-11 at 15 50 00](https://github.com/user-attachments/assets/f4f82319-cd0e-4da0-a99e-9b9d3feaa68b)
nshot 2025-01-11 at 15.49.53.png…]()

**Comment by ich777** [comment]
> As you can see, the container is up but the 14003 door is not working.

And you are sure that the application in the container storagenode-rio container is actually running on port 14003 since if this application is running still on 14002 this won't work.

The screenshot from above shows that the connection is refused, are you really sure that everything with your containers is working correctly?

I just took a quick look into the container template for storagenode and if it is still running on port 14002 inside the container you have to put a port forwarding in the OpenVPN-Client template with the container port:14002 and host port 14003 then you will be actually be able to reach the WebUI.
Since I assume this is what you did in the template from storagenode-rio

You have to understand the storagenode-rio has basically no network anymore because the container uses the network from OpenVPN-Client and therefore you have do insert all port mappings into the OpenVPN-Client container exactly as they are in the storeagenode-rio template because now all traffic is routed through the OpenVPN-Client container and none of the port mappings in the storagenode-rio container are working any more because it has no own network any more.

Hope that makes sense.
